services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hh}
      POSTGRES_USER: ${POSTGRES_USER:-hh}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hh}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-hh} -d ${POSTGRES_DB:-hh}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  cache:
    image: redis:7-alpine
    command: ["redis-server","--save","60","1","--loglevel","warning"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    working_dir: "/app/HH бот"
    environment:
      PYTHONPATH: "/app:/app/HH бот"
      TZ: ${TZ:-UTC}
    command:
      - sh
      - -lc
      - "python -m uvicorn $${APP_MODULE:-backend.app.main:app} --host 0.0.0.0 --port $${WEB_PORT:-8000}"
    expose:
      - "8000"
    volumes:
      - web_logs:/var/log/app
    healthcheck:
      test: ["CMD","python","-c","import os,socket; s=socket.socket(); s.settimeout(1); s.connect(('127.0.0.1', int(os.getenv('WEB_PORT','8000')))); s.close()"]
      interval: 10s
      timeout: 3s
      retries: 12
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/bot/entrypoint.sh"]
    env_file:
      - ./.env
    environment:
      PYTHONPATH: "/app:/app/HH бот"
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:?TELEGRAM_BOT_TOKEN is required}
      BOT_TOKEN: ${BOT_TOKEN:-${TELEGRAM_BOT_TOKEN}}
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-hh}:${POSTGRES_PASSWORD:-hh}@db:5432/${POSTGRES_DB:-hh}
      REDIS_URL: redis://cache:6379/0
      BOT_LOG_DIR: /var/log/app
      BOT_LOG_FILE: /var/log/app/bot.log
      TZ: ${TZ:-UTC}
    volumes:
      - botlogs:/var/log/app
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    healthcheck:
      # Без pgrep: читаем командную строку PID 1 и ищем наш runner.py
      test: ["CMD-SHELL", "tr '\\0' ' ' </proc/1/cmdline | grep -q 'HH бот/bot/runner.py'"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    healthcheck:
      # Только статический healthz — больше никаких 502
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
  botlogs:
  web_logs:
